### ISSUE TITLE
Error when trying single_pair_dataset example

### ISSUE THREAD

**Issue by yuqiusanofi** [ketatam/DiffDock-PP#8]
Errors when testing the single_pair_dataset example (1A2K):
Total time spent: 169.33692002296448
ligand_rmsd_summarized: {'mean': 23.944883, 'median': 23.944883, 'std': 0.0, 'lt1': 0.0, 'lt2': 0.0, 'lt5': 0.0, 'lt10': 0.0}
complex_rmsd_summarized: {'mean': 14.106365, 'median': 14.106365, 'std': 0.0, 'lt1': 0.0, 'lt2': 0.0, 'lt5': 0.0, 'lt10': 0.0}
interface_rmsd_summarized: {'mean': 9.92274, 'median': 9.92274, 'std': 0.0, 'lt1': 0.0, 'lt2': 0.0, 'lt5': 0.0, 'lt10': 100.0}
Traceback (most recent call last):
  File "/common/workdir/DiffDock-PP/src/main_inf.py", line 620, in <module>
    main()
  File "/common/workdir/DiffDock-PP/src/main_inf.py", line 354, in main
    dump_predictions(args,results)
  File "/common/workdir/DiffDock-PP/src/main_inf.py", line 383, in dump_predictions
    with open(args.prediction_storage, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'storage/run_on_pdb_pairs.pkl'

**Comment by ketatam** [comment]
Hi! Thanks for your interest in our work and for raising this issue.

You get this error because the folder `storage` does not exist and was not pushed along with the code. You can simply solve it by creating a folder named `storage` in the main repo.
