### ISSUE TITLE
E3NN vs Diffusion 

### ISSUE THREAD

**Issue by kevinbdsouza** [ketatam/DiffDock-PP#9]
Hi, 

The default model_type in args.py is "diffusion" but in factory.py the model is loaded only if the model_type is "e3nn" and raises an exception otherwise. Could you explain what's going on here? 

Thanks, 

Kevin

**Comment by ketatam** [comment]
Hi Kevin, 

Thanks for your interest in our work and for pointing out this issue. 

The "diffusion" model_type is just legacy code from previous experiments and there is no intended difference between the two types. We have only one single model_type in this sense and it is "e3nn". I will update the args.py to reflect this.

Sorry for the confusion!

Amine
